version: '3'

services:
  database:
    build: ./Database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    ports:
      - "${MYSQL_TCP_PORT}:3306"
    expose:
      - ${MYSQL_TCP_PORT}
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10

  backend:
    build: ./Backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8090:8090"
